### PR TITLE
Define Annotator interface and related factory

### LINKED ISSUE #33: Define Annotator Interface and Related Factory
Annotators should have a common interface. The types implementing that interface should be instantiated via a factory pattern. For this initial task, use a "mock" type that can be passed to the factory and return a stub. This will be helpful for later unit test implementation.

Proposed interface definition should expose a "make" method with the following parameters

`context` – essentially a PropertyBag into which arbitrary data can be passed
`data` – byte[]
The method should result in a contract instance of an Annotation but allow for exceptions to be thrown if they occur.

### PR DESCRIPTION
**Pull request by KarimElghamry**
* Add annotator interface
* Add general AnnotatorException type
* Add KeyInfo class as a java bean
* Add SignatureInfo class as a java bean
* Implement MockAnnotator which is used in unit tests
* Implement and expose AnnotatorFactory class
* Implement all related unit tests

Fix #33

Signed-off-by: Karim Elghamry <karimelghamry@gmail.com>

### CODE REVIEW

File: src/main/java/com/alvarium/utils/ImmutablePropertyBag.java [hunk 1]
```diff
@@ -0,0 +1,24 @@
+package com.alvarium.utils;
+
+import java.util.HashMap;
+import java.util.Map;
+
+public class ImmutablePropertyBag implements PropertyBag {
```
Comment (KarimElghamry) [inline src/main/java/com/alvarium/utils/ImmutablePropertyBag.java:6]: `PropertyBag` implementation was taken from the PR #30

File: src/main/java/com/alvarium/utils/PropertyBag.java [hunk 2]
```diff
@@ -0,0 +1,9 @@
+package com.alvarium.utils;
+
+import java.util.Map;
+
+public interface PropertyBag {
```
Comment (KarimElghamry) [inline src/main/java/com/alvarium/utils/PropertyBag.java:5]: `PropertyBag` implementation was taken from the PR #30

File: src/main/java/com/alvarium/annotators/Annotator.java [hunk 3]
```diff
@@ -0,0 +1,18 @@
...
+ */
+public interface Annotator {
+  /**
+   * creates an Annotation from the given raw data
+   * @param ctx
+   * @param data
+   * @return Annotation object
+   * @throws AnnotatorException
+   */
+  public Annotation make(PropertyBag ctx, byte[] data) throws AnnotatorException;
```
Comment (KarimElghamry) [inline src/main/java/com/alvarium/annotators/Annotator.java:17]: the `make` method in the java sdk represents the `Do` function in go. I couldn't go with the same go naming convention as `do` is a keyword in java. I assume `Do` was chosen in the go sdk because `make` is a keyword in go.

**Comment by KarimElghamry** [comment]
Rebased with latest main updates in c0bafdffb4ebe975d7f56b98ce49a2bf5e14f303

File: src/main/java/com/alvarium/annotators/AnnotatorFactory.java [hunk 4]
```diff
@@ -0,0 +1,18 @@
+package com.alvarium.annotators;
+
+import com.alvarium.contracts.AnnotationType;
+import com.alvarium.hash.HashType;
+import com.alvarium.sign.SignatureInfo;
+
+public class AnnotatorFactory {
+
+  public Annotator getAnnotator(AnnotationType kind, HashType hash, SignatureInfo signature)
```
Comment (KarimElghamry) [inline src/main/java/com/alvarium/annotators/AnnotatorFactory.java:9]: Once the issue #38 is implemented, the annotator factory will only require `AnnotationType` and `SdkInfo` params as an input. `HashType` and `SignatureInfo` will be encapsulated inside `SdkInfo`.

File: src/main/java/com/alvarium/annotators/Annotator.java (hunk 3 above)
Comment (tsconn23) [reply src/main/java/com/alvarium/annotators/Annotator.java:17]: I think `execute` would be a better substitute. `make` is not a reserved word in Go but it does refer to the build tools as in the `Makefile`. If we needed to standardize on the API across implementations, I think `execute` is a better choice as we're asking the Annotator implementation to execute/do its verification.

So please rename accordingly to `execute`

**Review by tsconn23 — CHANGES_REQUESTED** [review]

**Comment by KarimElghamry** [comment]
changed from `make` to `execute` in ca463faac57844822760441a6a1911874ac9fd35 and rebased.

**Review by tsconn23 — APPROVED** [review]
